trigger:
- main

pool:
  name: Default   # ✅ use your self-hosted agent

steps:
- script: echo "Installing Node..."
  displayName: Install Node

- script: |
    echo "Running App"
    node app.js
  displayName: Run App

- script: echo "Build Successful 🎉"
  displayName: Build Complete
